apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ipnfyi

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# To apply:
# kubectl apply -k k8s/
